language: node_js

node_js:
- '0.10'
- '0.12'
- '4'
- '6'
- '8'

branches:
  only:
  - master

before_script:
- npm install -g grunt-cli
- grunt --version

notifications:
  on_success: never
